FROM dawidmalina/pinpoint-agent:1.7.0

# https://github.com/dawidmalina/docker-pinpoint/blob/master/pinpoint-agent/Dockerfile
RUN sed -i "s/profiler.sampling.rate=20/profiler.sampling.rate=1/g" /assets/pinpoint.config